CREATE TYPE "public"."option_side" AS ENUM('buy', 'sell');--> statement-breakpoint
CREATE TYPE "public"."option_type" AS ENUM('call', 'put');--> statement-breakpoint
CREATE TYPE "public"."sentiment_label" AS ENUM('BULLISH', 'NEUTRAL', 'BEARISH');--> statement-breakpoint
CREATE TYPE "public"."strategy" AS ENUM('OPTIONS', 'UNKNOWN');--> statement-breakpoint
CREATE TABLE "classifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "classifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"post_id" bigint,
	"comment_id" bigint,
	"sentiment_label" "sentiment_label" NOT NULL,
	"sentiment_score" numeric(4, 3) NOT NULL,
	"confidence" numeric(4, 3) NOT NULL,
	"strategy" "strategy" DEFAULT 'UNKNOWN' NOT NULL,
	"time_horizon" text,
	"is_options" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "classifications_one_parent" CHECK ((
        ("classifications"."post_id" is not null and "classifications"."comment_id" is null)
        or
        ("classifications"."post_id" is null and "classifications"."comment_id" is not null)
      ))
);
--> statement-breakpoint
CREATE TABLE "comment_ticker_map" (
	"comment_id" bigint NOT NULL,
	"ticker_id" bigint NOT NULL,
	"confidence" numeric(4, 3) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "comment_ticker_map_pk" PRIMARY KEY("comment_id","ticker_id")
);
--> statement-breakpoint
CREATE TABLE "comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reddit_id" text NOT NULL,
	"post_id" bigint,
	"parent_reddit_id" text NOT NULL,
	"subreddit_id" bigint NOT NULL,
	"author" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"body" text NOT NULL,
	"ingested_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hourly_ticker_aggregates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hourly_ticker_aggregates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ticker_id" bigint NOT NULL,
	"hour_bucket" timestamp with time zone NOT NULL,
	"avg_weighted_score" numeric(12, 6) NOT NULL,
	"bullish_count" integer DEFAULT 0 NOT NULL,
	"bearish_count" integer DEFAULT 0 NOT NULL,
	"neutral_count" integer DEFAULT 0 NOT NULL,
	"total_mentions" integer DEFAULT 0 NOT NULL,
	"sentiment_label" "sentiment_label" NOT NULL,
	"calculated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hourly_ticker_strategy_aggregates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hourly_ticker_strategy_aggregates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ticker_id" bigint NOT NULL,
	"strategy" "strategy" NOT NULL,
	"hour_bucket" timestamp with time zone NOT NULL,
	"avg_weighted_score" numeric(12, 6) NOT NULL,
	"bullish_count" integer DEFAULT 0 NOT NULL,
	"bearish_count" integer DEFAULT 0 NOT NULL,
	"neutral_count" integer DEFAULT 0 NOT NULL,
	"total_mentions" integer DEFAULT 0 NOT NULL,
	"sentiment_label" "sentiment_label" NOT NULL,
	"calculated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "metrics_snapshots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "metrics_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"post_id" bigint,
	"comment_id" bigint,
	"captured_at" timestamp with time zone DEFAULT now() NOT NULL,
	"score" integer NOT NULL,
	"comment_count" integer,
	CONSTRAINT "metrics_snapshots_one_parent" CHECK ((
        ("metrics_snapshots"."post_id" is not null and "metrics_snapshots"."comment_id" is null)
        or
        ("metrics_snapshots"."post_id" is null and "metrics_snapshots"."comment_id" is not null)
      ))
);
--> statement-breakpoint
CREATE TABLE "option_legs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "option_legs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"classification_id" bigint NOT NULL,
	"side" "option_side" NOT NULL,
	"type" "option_type" NOT NULL,
	"strike" numeric(12, 4),
	"expiry" date,
	"quantity" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "post_ticker_map" (
	"post_id" bigint NOT NULL,
	"ticker_id" bigint NOT NULL,
	"confidence" numeric(4, 3) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "post_ticker_map_pk" PRIMARY KEY("post_id","ticker_id")
);
--> statement-breakpoint
CREATE TABLE "posts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reddit_id" text NOT NULL,
	"subreddit_id" bigint NOT NULL,
	"author" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"title" text NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"ingested_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "subreddits" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subreddits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"last_crawled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tickers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tickers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"symbol" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "classifications" ADD CONSTRAINT "classifications_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "classifications" ADD CONSTRAINT "classifications_comment_id_comments_id_fk" FOREIGN KEY ("comment_id") REFERENCES "public"."comments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comment_ticker_map" ADD CONSTRAINT "comment_ticker_map_comment_id_comments_id_fk" FOREIGN KEY ("comment_id") REFERENCES "public"."comments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comment_ticker_map" ADD CONSTRAINT "comment_ticker_map_ticker_id_tickers_id_fk" FOREIGN KEY ("ticker_id") REFERENCES "public"."tickers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_subreddit_id_subreddits_id_fk" FOREIGN KEY ("subreddit_id") REFERENCES "public"."subreddits"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hourly_ticker_aggregates" ADD CONSTRAINT "hourly_ticker_aggregates_ticker_id_tickers_id_fk" FOREIGN KEY ("ticker_id") REFERENCES "public"."tickers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hourly_ticker_strategy_aggregates" ADD CONSTRAINT "hourly_ticker_strategy_aggregates_ticker_id_tickers_id_fk" FOREIGN KEY ("ticker_id") REFERENCES "public"."tickers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "metrics_snapshots" ADD CONSTRAINT "metrics_snapshots_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "metrics_snapshots" ADD CONSTRAINT "metrics_snapshots_comment_id_comments_id_fk" FOREIGN KEY ("comment_id") REFERENCES "public"."comments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "option_legs" ADD CONSTRAINT "option_legs_classification_id_classifications_id_fk" FOREIGN KEY ("classification_id") REFERENCES "public"."classifications"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_ticker_map" ADD CONSTRAINT "post_ticker_map_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_ticker_map" ADD CONSTRAINT "post_ticker_map_ticker_id_tickers_id_fk" FOREIGN KEY ("ticker_id") REFERENCES "public"."tickers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_subreddit_id_subreddits_id_fk" FOREIGN KEY ("subreddit_id") REFERENCES "public"."subreddits"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "classifications_post_unique" ON "classifications" USING btree ("post_id") WHERE "classifications"."post_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "classifications_comment_unique" ON "classifications" USING btree ("comment_id") WHERE "classifications"."comment_id" is not null;--> statement-breakpoint
CREATE INDEX "classifications_strategy_idx" ON "classifications" USING btree ("strategy");--> statement-breakpoint
CREATE INDEX "comment_ticker_map_ticker_idx" ON "comment_ticker_map" USING btree ("ticker_id");--> statement-breakpoint
CREATE UNIQUE INDEX "comments_reddit_id_unique" ON "comments" USING btree ("reddit_id");--> statement-breakpoint
CREATE INDEX "comments_subreddit_created_idx" ON "comments" USING btree ("subreddit_id","created_at");--> statement-breakpoint
CREATE INDEX "comments_post_id_idx" ON "comments" USING btree ("post_id");--> statement-breakpoint
CREATE UNIQUE INDEX "hourly_ticker_aggregates_unique" ON "hourly_ticker_aggregates" USING btree ("ticker_id","hour_bucket");--> statement-breakpoint
CREATE INDEX "hourly_ticker_aggregates_hour_idx" ON "hourly_ticker_aggregates" USING btree ("hour_bucket");--> statement-breakpoint
CREATE UNIQUE INDEX "hourly_ticker_strategy_aggregates_unique" ON "hourly_ticker_strategy_aggregates" USING btree ("ticker_id","strategy","hour_bucket");--> statement-breakpoint
CREATE INDEX "hourly_ticker_strategy_hour_idx" ON "hourly_ticker_strategy_aggregates" USING btree ("hour_bucket");--> statement-breakpoint
CREATE INDEX "metrics_snapshots_post_captured_idx" ON "metrics_snapshots" USING btree ("post_id","captured_at");--> statement-breakpoint
CREATE INDEX "metrics_snapshots_comment_captured_idx" ON "metrics_snapshots" USING btree ("comment_id","captured_at");--> statement-breakpoint
CREATE INDEX "option_legs_classification_idx" ON "option_legs" USING btree ("classification_id");--> statement-breakpoint
CREATE INDEX "post_ticker_map_ticker_idx" ON "post_ticker_map" USING btree ("ticker_id");--> statement-breakpoint
CREATE UNIQUE INDEX "posts_reddit_id_unique" ON "posts" USING btree ("reddit_id");--> statement-breakpoint
CREATE INDEX "posts_subreddit_created_idx" ON "posts" USING btree ("subreddit_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "subreddits_name_unique" ON "subreddits" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "tickers_symbol_unique" ON "tickers" USING btree ("symbol");